# -*- coding: utf-8 -*-
"""[Day1]JumpToPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J9A08DDRpaoRd_ULgwxQkE-OsbIBkoQz
"""

print('hello')

print('안녕하세요.', end=' ')
print('저는 홍길동입니다.')

# 설명을 씀, 컨트롤 / , comment 혹은 주석
# 입력 : 데이터를 가지고 와야함.
# 처리 : 적절한 처리
# 출력 : 처리한 결과를 내보내는 일(모니터, 파일 , DB저장, 네트워크 전송)

name = input('이름을 입력하세요 >> ') # 간단한 처리(기호를 쓴다) : 연산 => 표시를 한다면 '연산자' 가 된다.
# = : 대입 연산자(등호 성립)

print(name)

call = input('이름을 입력하세요 >> ')
group = input('소속을 입력하세요 >> ')
number = input('번호를 입력하세요 >> ')

print(name, group, number)

location = '신촌'

number = 2

height = 195.5

food_lunch = True  # _ 붙으면 스네이크 표기법, 대문자로 쓰면 카멜표기법(java 에서 사용)

print(location)

location2 = ["신촌", "강남"]

print(location2[0])

age2 = input('나이 입력 >> ') # 컴퓨터에서 입력한 데이터는 type을 str으로 인식한다.
print(int(age2) + 1) # str을 int로 변경

age3 = str(194)
print(age3 + '1')

age4 = input('나이 입력 >>> ')
print('내년 나이는 ', int(age4) + 1)

number1 = input('숫자를 입력하세요 >> ')
number2 = input('숫자를 입력하세요 >> ')

plus = int(number1) + int(number2)
print('더한다면 다음과 같은 수가 나옵니다 ', plus)

minus = int(number1) - int(number2)
print('뺀다면 다음과 같은 수가 나옵니다', minus)

calculate = int(number1) * int(number2) # *을 아스테리크, 에스테리크 라고 부름.
print('곱한다면 다음과 같은 수가 나옵니다', calculate)

divide = int(number1) / int(number2)
print('나눈다면 다음과 같은 수가 나옵니다', divide)

me = '커피'
me2 = '우유'
print(me + me2)
price = 1000

see = 4+9
print(see)

see = '13'
print(see + '1')

print(int(see) + 1)

print(me + me2 + ' 가격은 ' + str(price) + '원')

5 % 2 # % 는 나눈 나머지

5 // 2 # //는 나누었을때 몫

coffee_cost = input('커피값 입력 >> ')
count = input('인원수 >> ')
sum = int(coffee_cost) * int(count) # 변수(저장공간, 저장공간이름 = 변수명)

if(sum >= 20000):
  print('2000원 할인해 드립니다', sum-2000)
  
else:
  print('계산값을 다 지불하셔야 합니다.', sum)

deposit = input('1년 만기 정기 예금을 얼마나 예치하시겠습니까? ')
interest = int(deposit) / 10
print('원금이 ' + deposit + '원이시군요.!')
print('이자는 ' + str(interest) + '원입니다.')
sum = int(deposit) + interest
print('원리합계는 ' + str(sum) + '원입니다.')

english = input('영어점수 입력 : ')
math = input('수학점수 입력 : ')
korean = input('국어점수 입력 : ')
print('--------------')
sum = int(english) + int(math) + int(korean)
avg = (int(english) + int(math) + int(korean)) / 3
print('세 과목의 합은 ' + str(sum) + '점')
print('세 과목의 평균은 ', int(avg), '점')

nowtime = input('지금은 몇 시 입니까? ')
if(int(nowtime) < 12):
  print('점심 전입니다. 맛있게 드세요.!')
else:
  print('점심 후입니다.')

id = input('아이디를 입력하세요. ')
if(id == 'root'):
  print('로그인 되었습니다.')
elif(id == 'root1'):
  print('로그인되지 않았습니다.')

sticker = input('구매한 스티커 갯수를 입력하세요 ')
bookmark = input('구매한 책갈피 갯수를 입력하세요 ')
sticker_price = int(sticker) * 1000
bookmark_price = int(bookmark) * 2500
total_price = bookmark_price + sticker_price
my_price = 0.9 * total_price
print('제가 낸 금액은 ', int(my_price), '원 입니다.')